[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
audiopus = { version = "0.2.0", features = ["encoder"] }
bincode = "1.3.3"
cpal = "0.17.1"
eframe = "0.31.0"
iced = "0.14.0"
image = "0.25.9"
mdns-sd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
tray-icon = "0.21.3"
winit = "0.30.12"
raw-window-handle = "0.6"
socket2 = "0.5.8"
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
